version: '3.4'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: kafkacdc_mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=depositdb

  elasticsearch:
    image: 'elasticsearch:6.6.0'
    ports:
      - 9209:9200
      - 9300:9300
    container_name: kafkacdc_elastic
    restart: always
    environment:
      - discovery.type=single-node
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9093"
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    depends_on:
      - zookeeper
      - mongodb

  connector:
    image: debezium/connect:0.10
    ports:
      - "8083:8083"
    container_name: connector
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - zookeeper
      - mongodb
      - kafka

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager
    ports:
      - "9009:9000"
    links:
     - zookeeper
     - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      KM_ARGS: -Djava.net.preferIPv4Stack=true

  kafkacdc.kafkaconnectconfigureconsole:
    image: ${DOCKER_REGISTRY-}kafkacdckafkaconnectconfigureconsole
    build:
      context: .
      dockerfile: KafkaCDC.KafkaConnectConfigureConsole/Dockerfile
    depends_on:
      - zookeeper
      - mongodb
      - kafka

  kafkacdc.fillmongoconsole:
    image: ${DOCKER_REGISTRY-}kafkacdcfillmongoconsole
    build:
      context: .
      dockerfile: KafkaCDC.FillMongoConsole/Dockerfile
    depends_on:
      - zookeeper
      - mongodb
      - kafka
      - kafkacdc.kafkaconnectconfigureconsole

  kafkacdc.projectionconsole:
    image: ${DOCKER_REGISTRY-}kafkacdcprojectionconsole
    build:
      context: .
      dockerfile: KafkaCDC.ProjectionConsole/Dockerfile
    depends_on:
      - zookeeper
      - mongodb
      - kafka
      - kafkacdc.kafkaconnectconfigureconsole

  kafkacdc.queryapi:
    image: ${DOCKER_REGISTRY-}kafkacdcqueryapi
    build:
      context: .
      dockerfile: KafkaCDC.QueryApi/Dockerfile
    depends_on:
      - zookeeper
      - mongodb
      - kafka
      - kafkacdc.projectionconsole